// TODO: 
//   Save to localStorage
//   Fix eraser/add new eraser functionality
//   Remove unnecessary runs of false (generated by erasing) or identical points using array.filter((x, i, a) => !i || x !== a[i-1]) [https://stackoverflow.com/questions/58266822/merge-arrays-consecutive-items-when-equal#58266948]

var cnv;

var points = [];

var strokeColour;
var eraser = false;
var eraserSize = 50;

var setup = function() {
    cnv = createCanvas(windowWidth, windowHeight);
    cnv.elt.addEventListener('pointerdown', function(event) {
        eraser = event.button === 5;
    }, true);
    
    strokeColour = color(0);
};

var draw = function() {
    background(255);
    stroke(strokeColour); // move inside loop later when diff colours available
    for (let p = 0; p < points.length-1; p++) {
        if (points[p] && points[p+1]) line(points[p][0], points[p][1], points[p+1][0], points[p+1][1]);
    }
};

var mousePressed = function() {
    if (!eraser) points.push(false, [mouseX, mouseY]);
};

var mouseDragged = function() {
    // use dist() instead for circular eraser
    if (eraser) points = points.filter(p => p ? p[0]+eraserSize/2 <= mouseX && p[0]-eraserSize/2 >= mouseX && p[1]+eraserSize/2 <= mouseY && p[1]-eraserSize/2 >= mouseY : true);
    else points.push([mouseX, mouseY]);
};

var mouseReleased = function() {
    if (!eraser) points.push([mouseX, mouseY]);
    // add a save to localStorage here
};

var windowResized = function() {
    resizeCanvas(windowWidth, windowHeight);
};
